name: SignClick
version: 1.0.0
author: klanting
main: com.klanting.signclick.SignClick
api-version: 1.18
commands:
  signclick:
    description: all info about the signclick plugin
    usage: /<command>
  signclickpos:
    description: mark the teleport endpoint position
    usage: /<command>
  country:
    description: president commands
    usage: /<command>
  discord:
    description: get the discord url
    usage: /<command>
  dynmap:
    description: get the dynmap.
    usage: /<command>
  weeklypay:
    description: set a payment towards a person that pays every week.
    usage: /<command>
  company:
    description: use the company commands.
    usage: /<command>
  party:
    description: use the party commands.
    usage: /<command>

localization:
  default: en_US
  supported: [en_US]

signclick.use:
  description: Allows using the main feature of the plugin.
  default: true
  signclick.staff:
    description: Allows access to staff features.
    default: op
    children:
      signclick.use: true

depend: [Vault]
softdepend: [dynmap]
